version: '3.7'
services:
    mysql:
        image: 'mysql:latest'
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: db_blog
        ports:
            - "3307:3306"
