kernel:
    resource: ../src/Kernel.php
    type: annotation

users.registration:
    path: /users
    controller: App\Security\Infrastructure\Http\Registration\RegistrationController
    methods: [POST]
